# Generated by Django 3.2.13 on 2022-05-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your post title', max_length=256)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog-images/')),
            ],
        ),
    ]
