# Generated by Django 3.2.13 on 2022-05-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
    ]
